### PR TITLE
Whole structure of this repo has been changed

### PR DESCRIPTION
**Pull request by Girishbari**
## Fixed Issue #49  
I have made modifications to the structure of this repo, while doing this there were lots of issues as they were no single 
the links between files and folders, I have tried my best to overcome this problem

## Changes proposed
Please @Sajiyah-Salat  Update the ReadMe and put a message about restructuring 
1. Tell the contributors to make necessary HTML files in the public folder only AND
2. If anyone wants to add a CSS file then there is again another folder in public, you can add CSS file there and give necessary to your HTML

### CODE REVIEW

**Review by Sajiyah-Salat — APPROVED** [review]
Great work!

**Comment by Sajiyah-Salat** [comment]
Hello @Girishbari you have done a great work Thank you for that! but I think the work is still there if we make one html one css and one image folder it will be more beneficial for the new comers. Let me know what you think about that. Can I know your social handle as I appreciate people for thier good work on my profile.

**Comment by Girishbari** [comment]
sure @Sajiyah-Salat I already have sent a request to you on LinkedIn you can check there 
What are you telling I already tried but due to its improper structure some CSS was not working properly so I was not able to make a separate folder for CSS, HTML, and Images?
However, just update the Readme of this repo so that newcomers will update or make a new files in respected manner

**Comment by Sajiyah-Salat** [comment]
Ohk I will try to do it..And check the readme I have already updated it with what you have told. Thank for contributing in BlogWeb. if you want to make more contributions there are issues open, have a look at it.
Happy Coding

**Pull request merged**
