### PR TITLE
PR for search page

### PR DESCRIPTION
**Pull request by uybera**
- Correction nav href in search page
- Reuse home page header for the homogeneity of the site 
- Display 3 articles per row

** I noticed that you have the web site 2 times in your repo (root and public/ ). I modified the file in the root.

If you want some other modifications, I'm open.

Thanks giving me the opportunity for my first pull request !

### CODE REVIEW

**Comment by Sajiyah-Salat** [comment]
@uybera Thanks for your contribution your pr will be shortly review and merge by the maintainer.

**Comment by Sajiyah-Salat** [comment]
Hey @uybera I appreciate your work. But it could be more perfect if you do these things
Articles will look much better if you put them vertically 
my blogs are already written you can add that link directly 
Hope you understand. Looking forward to collaborate on more such work.

**Comment by uybera** [comment]
Hello @Sajiyah-Salat ,
I've made the modification to display articles vertically.

Concerning your blogs, I don't see where you put them. 
I just see 2 blogs  :
- The charming Toaday  [blogspot2.html]
- The Miracle of Exercise  [blogspot.html]

but not the others.


Thanks;

**Comment by Sajiyah-Salat** [comment]
Thanks for contributing you pr will be merged after being reviewed by maintainer in 24 hours. Happy coding

**Comment by Sajiyah-Salat** [comment]
Hey @uybera I appreciate your work and changes you have made shows your progress but  I would like to know you that your pr is still not upto mark and you can do this to get it merged
Take inspiration from this : https://blogweb-c94c0.web.app/

put some sapce at left and make it little bit center
Remove line box from year 
**Excited for your pr to be merged**
Happy Coding

**Comment by uybera** [comment]
Hey @Sajiyah-Salat ,
I have taken your remarks into consideration.

Please tell me if any other modification is necessary.

Thanks,

**Comment by Sajiyah-Salat** [comment]
Hey can you please change the color to f8f3f3 of home-articles. What do you think if this color changes this will look good then... right?

**Comment by Sajiyah-Salat** [comment]
Hey @uybera can I know your LinkedIn handle as I want to give you shout out there because of your good work for community

**Pull request merged**
