### PR TITLE
Changed design completely for home page

### LINKED ISSUE #38: Used images are not present
The images used in the website are not present in the repo.

image

### PR DESCRIPTION
**Pull request by ShailavMalik**
fixes #38 #39 #40 
**Made a fresh new aesthetic design for the home page**

check below-attached screenshots for reference
<br>
desktop screen:
screencapture-127-0-0-1-5500-index-html-2022-10-28-20_35_26

<br>
mobile view:

screencapture-127-0-0-1-5500-index-html-2022-10-28-21_07_23

### CODE REVIEW

**Comment by ShailavMalik** [comment]
@Sajiyah-Salat Please check the PR and let me know if any changes are required

**Comment by Sajiyah-Salat** [comment]
Hey @ShailavMalik It's excellent and I m excited to get it to merge but can you please change the blog icon you can use this as well
https://github.com/Sajiyah-Salat/BlogWeb/blob/main/src/img/favicon.png
Thanks for your contribution, by the way, looking forward to collaborating on more such work.

**Comment by ShailavMalik** [comment]
@Sajiyah-Salat Ok

**Comment by ShailavMalik** [comment]
@Sajiyah-Salat Changed the webpage icon as you specify

check the deployment preview of this PR here
https://shailavmalik.github.io/BlogWeb/

**Comment by Sajiyah-Salat** [comment]
Hey @ShailavMalik Do you mind if I appreciate you on LinkedIn You did a great work for me...Thanks again

**Comment by ShailavMalik** [comment]
@Sajiyah-Salat yes!  u can tag me on LinkedIn

**Pull request merged**
