### PR TITLE
Fixed blog post pages - issue #44

### PR DESCRIPTION
**Pull request by alisha-takkar**

### CODE REVIEW

**Review by Sajiyah-Salat — APPROVED** [review]
Hello @alisha-takkar You have done a great work 
blogpage
But this big logo is just weird can you please reduce its size or done something else to increase the quality of ui.
also can you improve the bottom part as above. 
Thank you.

**Comment by alisha-takkar** [comment]
Sure @Sajiyah-Salat , I'll  have a look at it

**Comment by Sajiyah-Salat** [comment]
Hello alisha, How's your work going on and can you please tell why didn't you merge your pr.

**Comment by alisha-takkar** [comment]
Hey @Sajiyah-Salat  you will have to approve new changes before I can merge them

image

**Review by Sajiyah-Salat — APPROVED** [review]

**Comment by alisha-takkar** [comment]
Hey @Sajiyah-Salat  I still can't merge

image

**Comment by Sajiyah-Salat** [comment]
I have done the changes. let me know if further changes required.

**Comment by Sajiyah-Salat** [comment]
Hey, are you working on this issue?

**Comment by alisha-takkar** [comment]
No, it's resolved. This is final PR about this issue

**Pull request closed without merging**
