### PR TITLE
Web/preloader

### PR DESCRIPTION
**Pull request by UditDe**
Please review the preloader page that I'hv made. Here is the screenshot of that page below.
Screenshot (15)

### CODE REVIEW

**Comment by UditDe** [comment]
resolves issue #2

**Comment by UditDe** [comment]
@Sajiyah-Salat please review the changes and merge if there is no problem. It will be helpfull

**Comment by Sajiyah-Salat** [comment]
Sorry to say but the preloader needs improvement... I am happy to merge if you add nice design to it

**Comment by UditDe** [comment]
Ok, I'll be working on it

**Pull request closed without merging**
